# Generated by Django 5.1.6 on 2026-06-05 10:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSessaoEstudo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('produtividade', models.PositiveSmallIntegerField(choices=[(1, 'Muito Baixa'), (2, 'Baixa'), (3, 'Regular'), (4, 'Alta'), (5, 'Muito Alta')], help_text='Nota de 1 a 5 para o rendimento do estudante na sessão.')),
                ('descricao', models.TextField(blank=True, help_text='Anotações opcionais sobre o que atrapalhou ou ajudou no foco.', null=True)),
                ('hora_registro', models.DateTimeField(auto_now_add=True, help_text='Momento exato em que o feedback foi enviado.')),
            ],
            options={
                'verbose_name': 'Feedback da Sessão',
                'verbose_name_plural': 'Feedbacks das Sessões',
                'ordering': ['-hora_registro'],
            },
        ),
    ]
