# Generated by Django 5.1.6 on 2026-06-05 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback_sessao_estudo', '0001_initial'),
        ('sessao_estudo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacksessaoestudo',
            name='sessao_estudo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='sessao_estudo.sessaoestudo'),
        ),
    ]
