# Generated by Django 5.1.6 on 2026-06-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais_estudo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialestudo',
            name='aluno',
        ),
        migrations.RemoveField(
            model_name='materialestudo',
            name='arquivo_path',
        ),
        migrations.AddField(
            model_name='materialestudo',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='materiais/'),
        ),
        migrations.AlterField(
            model_name='materialestudo',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
