# Generated by Django 5.1.6 on 2026-06-04 00:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaDisciplina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('prazo', models.DateTimeField()),
                ('concluida', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('prioridade', models.CharField(choices=[('Baixa', 'Baixa'), ('Media', 'Média'), ('Alta', 'Alta')], default='Media', max_length=10)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_disciplina', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_disciplina', to='disciplinas.disciplina')),
            ],
            options={
                'verbose_name': 'Tarefa de Disciplina',
                'verbose_name_plural': 'Tarefas de Disciplina',
            },
        ),
    ]
