# Generated by Django 5.1.6 on 2026-06-05 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_remove_disciplina_carga_horaria_oficial_and_more'),
        ('eventos_academicos', '__first__'),
        ('tarefas_disciplina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefadisciplina',
            options={'ordering': ['prazo'], 'verbose_name': 'Tarefa de Disciplina', 'verbose_name_plural': 'Tarefas de Disciplina'},
        ),
        migrations.RemoveField(
            model_name='tarefadisciplina',
            name='aluno',
        ),
        migrations.AddField(
            model_name='tarefadisciplina',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='eventos_academicos.eventoacademico'),
        ),
        migrations.AlterField(
            model_name='tarefadisciplina',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='disciplinas.disciplina'),
        ),
        migrations.AlterField(
            model_name='tarefadisciplina',
            name='prioridade',
            field=models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta')], default='MEDIA', max_length=10),
        ),
    ]
