# Generated by Django 6.0.5 on 2026-06-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_aluno_data_nascimento'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='aluno',
            managers=[
            ],
        ),
    ]
