# Generated by Django 5.1.6 on 2026-06-05 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0002_remove_disciplina_carga_horaria_oficial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAcademico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('PROVA', 'Prova'), ('TRABALHO', 'Trabalho'), ('SEMINARIO', 'Seminário'), ('APRESENTACAO', 'Apresentação'), ('OUTRO', 'Outro')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_evento', models.DateField()),
                ('concluido', models.BooleanField(default=False)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_academicos', to='disciplinas.disciplina')),
            ],
            options={
                'verbose_name': 'Evento Acadêmico',
                'verbose_name_plural': 'Eventos Acadêmicos',
                'ordering': ['data_evento', 'titulo'],
            },
        ),
    ]
