# Generated by Django 5.1.6 on 2026-06-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_academicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoacademico',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventoacademico',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
