# Generated by Django 5.1.6 on 2026-07-07 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_id', models.CharField(max_length=120)),
                ('tipo', models.CharField(max_length=60)),
                ('util', models.BooleanField(help_text='True se o aluno marcou o insight como útil (👍), False se rejeitou (👎).')),
                ('motivo', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback de Insight',
                'verbose_name_plural': 'Feedbacks de Insight',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('aluno', 'insight_id'), name='insightfeedback_unico_por_aluno_e_insight')],
            },
        ),
    ]
