# Generated by Django 5.1.6 on 2026-06-05 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0002_remove_disciplina_carga_horaria_oficial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoEstudo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('duracao_realizada', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('AGENDADO', 'Agendado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_estudo', to='disciplinas.disciplina')),
            ],
            options={
                'verbose_name': 'Sessão de Estudo',
                'verbose_name_plural': 'Sessões de Estudo',
                'ordering': ['-inicio'],
            },
        ),
    ]
