# Generated by Django 5.1.6 on 2026-07-02 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_academicos', '0002_eventoacademico_hora_fim_eventoacademico_hora_inicio'),
        ('sessao_estudo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoestudo',
            name='evento_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_estudo', to='eventos_academicos.eventoacademico'),
        ),
    ]
