# Generated by Django 5.1.6 on 2026-07-01 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_remove_disciplina_carga_horaria_oficial_and_more'),
        ('sessao_estudo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioEstudo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Horário de Estudo',
                'verbose_name_plural': 'Horários de Estudo',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.RenameField(
            model_name='sessaoestudo',
            old_name='data_criacao',
            new_name='criada_em',
        ),
        migrations.AddField(
            model_name='sessaoestudo',
            name='atualizada_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sessaoestudo',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sessaoestudo',
            name='duracao_realizada',
            field=models.PositiveIntegerField(default=0, help_text='Minutos efetivamente estudados (líquido, sem pausas).'),
        ),
        migrations.AlterField(
            model_name='sessaoestudo',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20),
        ),
        migrations.AddField(
            model_name='sessaoestudo',
            name='horario_estudo',
            field=models.ForeignKey(blank=True, help_text='Bloco planejado que originou esta sessão, se houver.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='sessao_estudo.horarioestudo'),
        ),
        migrations.CreateModel(
            name='PlanejamentoDisciplina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carga_horaria_planejada', models.PositiveIntegerField(help_text='Carga horária planejada da semana, em minutos.')),
                ('observacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planejamentos_semanais', to='disciplinas.disciplina')),
            ],
            options={
                'verbose_name': 'Planejamento da Disciplina',
                'verbose_name_plural': 'Planejamento das Disciplinas',
                'ordering': ['disciplina__nome'],
            },
        ),
        migrations.AddField(
            model_name='horarioestudo',
            name='planejamento',
            field=models.ForeignKey(help_text='Planejamento semanal ao qual este horário pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='sessao_estudo.planejamentodisciplina'),
        ),
        migrations.CreateModel(
            name='SemanaEstudo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(help_text='Segunda-feira da semana, no horário local do aluno.')),
                ('data_fim', models.DateField(help_text='Domingo da semana, no horário local do aluno.')),
                ('ativa', models.BooleanField(default=True, help_text='True se esta é a semana corrente do aluno.')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semanas_estudo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semana de Estudo',
                'verbose_name_plural': 'Semanas de Estudo',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AddField(
            model_name='planejamentodisciplina',
            name='semana_estudo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planejamentos', to='sessao_estudo.semanaestudo'),
        ),
        migrations.AddField(
            model_name='sessaoestudo',
            name='semana_estudo',
            field=models.ForeignKey(blank=True, editable=False, help_text='Preenchido automaticamente pelo backend. Não enviado pelo cliente.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='sessao_estudo.semanaestudo'),
        ),
        migrations.AddIndex(
            model_name='sessaoestudo',
            index=models.Index(fields=['semana_estudo', 'status'], name='sessao_estu_semana__43cdfd_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaoestudo',
            index=models.Index(fields=['disciplina', 'status'], name='sessao_estu_discipl_0fc388_idx'),
        ),
        migrations.AddIndex(
            model_name='sessaoestudo',
            index=models.Index(fields=['inicio'], name='sessao_estu_inicio_bb9123_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessaoestudo',
            constraint=models.CheckConstraint(condition=models.Q(('fim__gt', models.F('inicio'))), name='sessao_fim_apos_inicio'),
        ),
        migrations.AddIndex(
            model_name='horarioestudo',
            index=models.Index(fields=['planejamento'], name='sessao_estu_planeja_d976c7_idx'),
        ),
        migrations.AddIndex(
            model_name='horarioestudo',
            index=models.Index(fields=['dia_semana', 'hora_inicio'], name='sessao_estu_dia_sem_cea6e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='horarioestudo',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fim__gt', models.F('hora_inicio'))), name='horario_fim_apos_inicio'),
        ),
        migrations.AddConstraint(
            model_name='horarioestudo',
            constraint=models.UniqueConstraint(fields=('planejamento', 'dia_semana', 'hora_inicio', 'hora_fim'), name='horario_unico_por_planejamento'),
        ),
        migrations.AddIndex(
            model_name='semanaestudo',
            index=models.Index(fields=['aluno', 'ativa'], name='sessao_estu_aluno_i_0fb7ab_idx'),
        ),
        migrations.AddIndex(
            model_name='semanaestudo',
            index=models.Index(fields=['aluno', '-data_inicio'], name='sessao_estu_aluno_i_47f762_idx'),
        ),
        migrations.AddConstraint(
            model_name='semanaestudo',
            constraint=models.UniqueConstraint(fields=('aluno', 'data_inicio'), name='unico_semana_por_aluno_e_inicio'),
        ),
        migrations.AddConstraint(
            model_name='semanaestudo',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__gte', models.F('data_inicio'))), name='semana_data_fim_apos_inicio'),
        ),
        migrations.AddIndex(
            model_name='planejamentodisciplina',
            index=models.Index(fields=['semana_estudo'], name='sessao_estu_semana__bfd667_idx'),
        ),
        migrations.AddIndex(
            model_name='planejamentodisciplina',
            index=models.Index(fields=['disciplina'], name='sessao_estu_discipl_18f1b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='planejamentodisciplina',
            constraint=models.UniqueConstraint(fields=('semana_estudo', 'disciplina'), name='planejamento_unico_por_semana'),
        ),
        migrations.AddConstraint(
            model_name='planejamentodisciplina',
            constraint=models.CheckConstraint(condition=models.Q(('carga_horaria_planejada__gt', 0)), name='planejamento_carga_positiva'),
        ),
    ]
