# Generated by Django 5.1.6 on 2026-07-07 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao_estudo', '0002_horarioestudo_and_more'),
        ('sessao_estudo', '0002_sessaoestudo_evento_academico'),
    ]

    operations = [
    ]
