# Generated by Django 5.1.6 on 2026-07-07 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessao_estudo', '0003_merge_20260707_0643'),
        ('sessao_estudo', '0005_bloco_encerrado_antecipadamente'),
    ]

    operations = [
    ]
